### ISSUE TITLE
Generate opendrr-boundaries.dump (was opendrr-boundaries.sql) on PR

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/boundaries#10]
When a PR is merged into this repo we need to generate the `opendrr-boundaries.sql` script. This script will be loaded into the stack on build eventually. So, on merge we spin up virtual machine, load the data, process the data, and export the .sql file.

**Comment by jvanulde** [comment]
Last update wasn't via PR, but rather a commit. Can we initiate an Action on commit as well as PR?

**Comment by wkhchow** [comment]
@jvanulde I just noticed the - opendrr-boundaries.sql.  Let me uncommit and branch/pr.

**Comment by wkhchow** [comment]
Reverted the commits in master and created new branch update_CDUID.  Will need to update opendrr-boundaries.sql in current branch.

https://github.com/OpenDRR/boundaries/issues/9

**Comment by anthonyfok** [comment]
Hi @wkhchow and @jvanulde,
When you have time, could you please share with me the steps to generate opendrr-boundaries.sql?
Is it from the "Importing Census Boundaries" step in add_data.sh , i.e. where the GeoPackage data are imported via ogr2ogr to PostgreSQL, and opendrr-boundaries.sql being the  the PostgreSQL dump of that data?
If this task is relatively urgent, I can try having a go at it tonight.

**Comment by wkhchow** [comment]
@anthonyfok  not urgent.  I can connect with you tomorrow on how I did it f needed.  I already generated the sql this time around via PGAdmin.

**Comment by anthonyfok** [comment]
Thanks @wkhchow!  No worries,  Joost told me more details, and it turns out to be the same process found in opendrr-api/python/add_data.sh.
