### ISSUE TITLE
Explore simplifying hexbin geometries 

### ISSUE THREAD

**Issue by wkhchow** [OpenDRR/boundaries#26]
Current hexbin geometries maybe too detailed in ES/leaflet most likely due to the amount of vertices along the shortline/coast.
May need to explore simplifying the coastline/hexbin geometries to reduce the amount of vertices (ST_simplify in postgis, simplify in QGIS).

**Comment by jvanulde** [comment]
How about not clipping at all?

**Comment by wkhchow** [comment]
@jvanulde following up and will create additional set of 1,5,10,25,50,100km unclipped.

**Comment by wkhchow** [comment]
after discussion, next version would be to include both clipped and unclipped hexbins at 1,5,10,25km and unclipped for 50km/100km
